name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Python ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '3.10.12'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: Instantiate
      run: |
        python -m pip install --upgrade pip
        # still using requirements.txt files as
        # https://github.com/pypa/pip/issues/11440
        pip3 install -r requirements.txt
    - name: Run Tests with code coverage report
      run: |
        pip install coverage
        coverage run -m pytest --capture=no
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
